name: clientlwm2miotr25
base: core16
version: V1
summary: IOTR 2.5 LwM2M Client
description: |
  LwM2M Client for IOTR 2.5
confinement: strict
grade: stable

apps:
  clientlwm2miotr25:
    command: clientlwm2miotr25
    daemon: simple
    plugs:
      - network
      - network-bind
      - snapd-control
      - shutdown
parts:
  client:
    override-build: |
      ./prepare.sh
    build-packages:
      - cmake
      - autoconf
    plugin: go
    source: .
    source-type: git
    go-importpath: launchpad.net/ce-web/alpaca
    go-channel: 1.15/stable
    
    
