name: alpaca
base: core16
version: V1
summary: IOTR 2.5 LwM2M Client
description: |
  LwM2M Client for IOTR 2.5
confinement: strict
grade: stable

apps:
  alpaca:
    command: cmd/alpaca
    plugs:
      - network
      - network-bind
      - snapd-control
      - shutdown
parts:
  client:
    override-build: |
      ./prepare.sh
    build-packages:
      - cmake
      - autoconf
    plugin: go
    source: .
    go-importpath: launchpad.net/ce-web/alpaca
    
    
