name: clientLwm2mIOTR25
base: core18
version: V1
summary: IOTR 2.5 LwM2M Client
description: |
  LwM2M Client for IOTR 2.5
confinement: strict
grade: stable

apps:
  clientLwm2mIOTR25:
    command: clientLwm2mIOTR25
    daemon: simple
    plugs:
      - network
      - network-bind
      - snapd-control
      - shutdown
parts:
  client:
    override-build: |
      ./prepare.sh
    build-packages:
      - cmake
      - autoconf
    plugin: go
    source: .
    source-type: local
    go-importpath: launchpad.net/ce-web/alpaca
    
    
